In [1]:
#Importing libraries:
import pandas as pd
import numpy as np

from sklearn.metrics import confusion_matrix, classification_report

import matplotlib.pyplot as plt

import tensorflow as tf
import keras
from tensorflow.keras import layers
from keras.datasets import mnist
from keras.layers import Dense, Activation, Dropout, Conv2D, Flatten, MaxPooling2D
from keras.models import Sequential

In [2]:
#Loading the dataset:
(X_train, Y_train),(X_test, Y_test)=mnist.load_data()

In [3]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [4]:
X_train.shape

(60000, 28, 28)

In [5]:
X_test.shape

(10000, 28, 28)

In [6]:
X_train.shape[0]

60000

In [7]:
#Preprocessing:
X_train=X_train.reshape(X_train.shape[0],28,28,1)
X_test=X_test.reshape(X_test.shape[0],28,28,1)
input_shape=(28,28,1)

In [8]:
X_train[0]

array([[[  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0]],

       [[  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0]],

       [[  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
      

In [9]:
X_train=X_train.astype('float32')
X_test=X_test.astype('float32')

In [10]:
X_train[0]

array([[[  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.]],

       [[  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.]],

       [[  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
    

In [11]:
X_train /= 255
X_test /= 255

In [12]:
X_train[0]

array([[[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ]],

       [[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        

In [13]:
#Convolutional layers and Neural Network procedure creation:
model=Sequential()
model.add(Conv2D(28,kernel_size=(3,3),input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(3,3)))
model.add(Flatten())
model.add(Dense(128,activation=tf.nn.relu))
model.add(Dense(10,activation='softmax'))

C:\Users\DELL\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [14]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [15]:
history=model.fit(X_train, Y_train,epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 25s 11ms/step - accuracy: 0.9499 - loss: 0.1696
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 28s 15ms/step - accuracy: 0.9819 - loss: 0.0587
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 34s 11ms/step - accuracy: 0.9867 - loss: 0.0415
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 20s 11ms/step - accuracy: 0.9904 - loss: 0.0302
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 21s 11ms/step - accuracy: 0.9929 - loss: 0.0209
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 20s 11ms/step - accuracy: 0.9951 - loss: 0.0156
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 21s 11ms/step - accuracy: 0.9960 - loss: 0.0124
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 20s 11ms/step - accuracy: 0.9972 - loss: 0.0093
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 22s 12ms/step - accuracy: 0.9974 - loss: 0.0082
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 21s 11ms/step - accuracy: 0.9974 - loss: 0.0075


In [16]:
model.evaluate(X_test,Y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9854 - loss: 0.0637


[0.0637260377407074, 0.9854000210762024]

In [17]:
Y_predicted=model.predict(X_test)
Y_predicted

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step


array([[1.5951426e-13, 1.0362295e-11, 4.4235640e-07, ..., 9.9999928e-01,
        5.7572615e-13, 5.2573363e-09],
       [5.4829933e-14, 4.0936143e-10, 1.0000000e+00, ..., 1.6107636e-21,
        5.4595698e-20, 4.3493901e-15],
       [4.1137299e-10, 9.9998665e-01, 6.4184218e-07, ..., 5.6783993e-08,
        1.0293373e-08, 2.6899696e-09],
       ...,
       [4.2470320e-21, 1.4074257e-14, 7.2837364e-16, ..., 1.4066005e-12,
        3.7997672e-10, 7.8215237e-07],
       [5.4833324e-16, 2.6832638e-15, 7.8745470e-17, ..., 3.4843412e-16,
        3.2335565e-06, 2.3316904e-12],
       [3.8218899e-13, 1.7243584e-19, 1.2848891e-13, ..., 7.7273487e-22,
        2.3739742e-14, 5.9617104e-17]], dtype=float32)

In [18]:
Y_predicted[0]

array([1.5951426e-13, 1.0362295e-11, 4.4235640e-07, 2.4370300e-07,
       1.0891148e-14, 2.1976469e-15, 3.4719301e-18, 9.9999928e-01,
       5.7572615e-13, 5.2573363e-09], dtype=float32)

In [19]:
Y_pred=np.argmax(Y_predicted,axis=1)

In [20]:
Y_pred

array([7, 2, 1, ..., 4, 5, 6], dtype=int64)

In [21]:
confusion_mat=confusion_matrix(Y_pred,Y_test)

In [22]:
confusion_mat

array([[ 972,    0,    1,    0,    0,    1,    2,    0,    3,    0],
       [   2, 1123,    0,    0,    0,    0,    2,    1,    0,    0],
       [   3,    2, 1023,    3,    1,    0,    2,   11,    2,    1],
       [   0,    2,    3, 1003,    0,   17,    1,    0,    6,    5],
       [   0,    1,    1,    0,  960,    0,    0,    0,    0,    3],
       [   0,    1,    0,    2,    0,  871,    2,    0,    2,    2],
       [   0,    3,    0,    0,    2,    2,  946,    0,    0,    0],
       [   1,    1,    2,    0,    0,    0,    0, 1006,    2,    0],
       [   1,    2,    1,    2,    0,    1,    2,    1,  952,    0],
       [   1,    0,    1,    0,   19,    0,    1,    9,    7,  998]],
      dtype=int64)

In [23]:
report=classification_report(Y_pred,Y_test)
print(report)

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       979
           1       0.99      1.00      0.99      1128
           2       0.99      0.98      0.98      1048
           3       0.99      0.97      0.98      1037
           4       0.98      0.99      0.99       965
           5       0.98      0.99      0.98       880
           6       0.99      0.99      0.99       953
           7       0.98      0.99      0.99      1012
           8       0.98      0.99      0.98       962
           9       0.99      0.96      0.98      1036

    accuracy                           0.99     10000
   macro avg       0.99      0.99      0.99     10000
weighted avg       0.99      0.99      0.99     10000

